// Include
#include "display.h"
#ifndef SETTINGS
#define SETTINGS

#define SETTING_TOUCHSCREEN_TIMER_PERIOD 10.0E-3
#define SETTING_GAME_TIMER_PERIOD 45.0E-3
#define SETTING_TOUCHSCREEN_TIMER_PERIOD 10.0E-3
#define SETTING_GAME_TIMER_PERIOD 45.0E-3

#define SETTING_TOTAL_DUCKS 4
#define SETTING_MAX_PLAYER_SHOTS 4
#define SETTING_MAX_DUCK_EGGS 4
#define SETTING_MAX_TOTAL_PROJECTILES                                              \
  (SETTING_MAX_PLAYER_SHOTS +                    \
   SETTING_MAX_DUCK_EGGS)
// Speed of eggs flying from duck
#define SETTING_DUCK_EGG_DISTANCE_PER_SECOND 35
#define SETTING_DUCK_EGG_DISTANCE_PER_TICK                                 \
  (SETTING_DUCK_EGG_DISTANCE_PER_SECOND * SETTING_GAME_TIMER_PERIOD)

// Speed of the shot from the gun
#define SETTING_PLAYER_SHOT_DISTANCE_PER_SECOND 350
#define SETTING_PLAYER_SHOT_DISTANCE_PER_TICK                                \
  (SETTING_PLAYER_SHOT_DISTANCE_PER_SECOND * SETTING_GAME_TIMER_PERIOD)

// Speed of DUCK
#define SETTING_DUCK_DISTANCE_PER_SECOND 40
#define SETTING_DUCK_DISTANCE_PER_TICK                                         \
  (SETTING_DUCK_DISTANCE_PER_SECOND * SETTING_GAME_TIMER_PERIOD)

#define SETTING_COLOR_PLAYER DISPLAY_YELLOW
#define SETTING_COLOR_DUCK DISPLAY_GREEN

#define SETTING_EXPLOSION_RADIUS 15

#endif /* SETTINGS */
	
